### PR TITLE
Fix fielddata fields on search and inner hits

### LINKED ISSUE #1366: Support for fielddata_fields on _search and inner hits
http://www.elastic.co/guide/en/elasticsearch/reference/1.5/search-request-fielddata-fields.html

Marking this as separate TODO also on inner hits while I am working on that not to get sidetracked.

### PR DESCRIPTION
**Pull request by gmarz**
This was largely implemented already but with a few issues.  I had to modify the code gen to skip the fielddata_fields param in order to work around https://github.com/elastic/elasticsearch/issues/11025.

Also modified the implementation on inner hits to be more consistent with search (i.e. `IList<PropertyPathMarker>` vs `IEnumerable<string>` and added an overload that accepts property path expressions).

Closes #1366

### CODE REVIEW

File: src/Nest/DSL/Search/InnerHitsDescriptor.cs [hunk 1]
```diff
@@ -79,7 +79,7 @@ public class InnerHitsDescriptor<T> : IInnerHits where T : class
 		bool? IInnerHits.Explain { get; set; }
 		ISourceFilter IInnerHits.Source { get; set; }
 		bool? IInnerHits.Version { get; set; }
-		IEnumerable<string> IInnerHits.FielddataFields { get; set; }
+		IList<PropertyPathMarker> IInnerHits.FielddataFields { get; set; }
```
Comment (Mpdreamz) [inline src/Nest/DSL/Search/InnerHitsDescriptor.cs]: ++ for catching this before releasing @gmarz !
