### PR TITLE
Expose Response on GetTaskResponse

### LINKED ISSUE #3963: GetTaskResponse does not expose Failures for reindex task
**NEST/Elasticsearch.Net version**:
7.0.1

**Elasticsearch version**:
7.2.0

**Description of the problem including expected versus actual behavior**:
Expected:
- `IsValid` to be `false` when `"failures" : []` response is not empty (just like `ReindexOnServerResponse.IsValid`
- Be able to read the `response.failures` of a reindex task

Actual:
- `IsValid` is `true` when ``"failures" : []`` is not empty

**Steps to reproduce**:
 1. Index documents into source index
 2. Create destination index with 0 replicas
 3. Create reindex task with `WaitForCompletion(false)`
 4. Poll status using `GetTaskAsync` using the `TaskId` and check `IsValid` and `Completed`
 5. Disconnect data node containing the shards of the indices

Response from `_tasks/<id>` includes `failures` (removed some fields for readability):

```
{
  "completed" : true,
  "task" : {
    "action" : "indices:data/write/reindex",
    "status" : {
      "total" : 2695491,
      "updated" : 0,
      "created" : 0,
      "deleted" : 0,
      "batches" : 499,
      "version_conflicts" : 498000,
      "noops" : 0
    },
    "description" : "reindex from [my-index-1] to [my-index-2]",
    "cancellable" : true
  },
  "response" : {
    "took" : 656338,
    "timed_out" : false,
    "total" : 2695491,
    "updated" : 0,
    "created" : 0,
    "deleted" : 0,
    "batches" : 499,
    "version_conflicts" : 498000,
    "noops" : 0,
    "failures" : [
      {
        "index" : "my-index-2",
        "type" : "_doc",
        "id" : "bowFbmoBnnQlcVPVmn7H",
        "cause" : {
          "type" : "node_not_connected_exception",
          "reason" : "[instance-0000000070][1.2.3.4:19437] Node not connected"
        },
        "status" : 500
      }
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by russcam**
This commit exposes Response on GetTaskResponse. Response is the response object for the action performed by the Task, so will vary by action. For this reason, expose Response as an internal LazyDocument, with a method to retrieve a TResponse from the deserialized LazyDocument bytes.

Closes #3963

### CODE REVIEW

File: src/Nest/Cluster/TaskManagement/GetTask/GetTaskResponse.cs [hunk 1]
```diff
@@ -9,5 +10,10 @@ public class GetTaskResponse : ResponseBase
 
 		[DataMember(Name = "task")]
 		public TaskInfo Task { get; internal set; }
+
+		[DataMember(Name = "response")]
+		internal LazyDocument Response { get; set; }
+
+		public TResponse GetResponse<TResponse>() where TResponse : class, IResponse => Response?.As<TResponse>();
```
Comment (codebrain) [inline src/Nest/Cluster/TaskManagement/GetTask/GetTaskResponse.cs]: Add some documentation around what properties on here make sense.

Comment (russcam) [reply src/Nest/Cluster/TaskManagement/GetTask/GetTaskResponse.cs]: I've addressed this in 9add6db. Also fixed a bug where the response must be deserialized with the `RequestResponseSerializer`

**Comment by russcam** [comment]
ported to 7.x in cc5efc4812545d53448272c6cc552ec3de5eb3ae
