### PR TITLE
Serialize DateMath with minimum 3 decimal places

### LINKED ISSUE #3719: 7.0.0-alpha 1 - Wrong converting datetime fields
I upgraded es to version 7 in our product.

I have one document with CreatedDate

[Date(Store = false)]
public DateTime CreatedDate { get; set; }

Then I have some DateRange query on CreatedDate.
In some case I got error for es server, depends on Date i pass.

{"took":4,"responses":[{"error":{"root_cause":[{"type":"date_time_parse_exception","reason":"date_time_parse_exception: Text '2019-05-06T07:38:35.82' could not be parsed, unparsed text found at index 19"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":4,"index":"sprint_loop_stream2","node":"UEMUX6kGRMSHdGfJC8KKhQ","reason":{"type":"parse_exception","reason":"failed to parse date field [2019-05-06T07:38:35.82] with format [strict_date_optional_time||epoch_millis]: [Text '2019-05-06T07:38:35.82' could not be parsed, unparsed text found at index 19]","caused_by":{"type":"date_time_parse_exception","reason":"date_time_parse_exception: Text '2019-05-06T07:38:35.82' could not be parsed, unparsed text found at index 19"}}}],"caused_by":{"type":"date_time_parse_exception","reason":"date_time_parse_exception: Text '2019-05-06T07:38:35.82' could not be parsed, unparsed text found at index 19"}},"status":400}]}

if date is
2019-05-06T07:38:35.82 query fails
if date is
2019-05-06T07:38:35.8200001 query succeced.

I suspect the new  internal serializer (utf8json)

### PR DESCRIPTION
**Pull request by russcam**
This commit ensures that DateMath containing DateTime are always serialized with a minimum of 3 decimal places.

https://github.com/elastic/elasticsearch/pull/41871 introduced a bug in Elasticsearch 7.x < 7.1.0 whereby date strings
with less than 3 decimal places throw a parser exception.

Fixes #3719

### CODE REVIEW

File: src/Tests/Tests.Reproduce/GitHubIssue3719.cs [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+		public void SerializeDateMathWithMinimumThreeDecimalPlacesWhenTens()
+		{
+			DateMath dateMath = new DateTime(2019, 5, 7, 12, 0, 0, 20);
+
+			var json = TestClient.Default.RequestResponseSerializer.SerializeToString(dateMath, RecyclableMemoryStreamFactory.Default);
+			json.Should().Be("\"2019-05-07T12:00:00.020\"");
+		}
+
+		[U]
+		public void SerializeDateMathWithMinimumThreeDecimalPlacesThenHundreds()
```
Comment (russcam) [inline src/Tests/Tests.Reproduce/GitHubIssue3719.cs]:
```suggestion
		public void SerializeDateMathWithMinimumThreeDecimalPlacesWhenHundreds()
```
