### PR TITLE
make sure we can parse exponential notation and tostring reflects the…

### LINKED ISSUE #2778: TimeParseException when Profile=true
**NEST/Elasticsearch.Net version**: 5.4.0

**Elasticsearch version**: 5.4.1

**Description of the problem including expected versus actual behavior**:
When I turn on profiling on my `SearchRequest`, NEST has a problem to deserialize request.
**Steps to reproduce**:
 1. Turn on profiling on the `SearchRequest` - `request.Profile = true`
 2. Execute working query, but with profiling on
 3. Get `TimeParseException`

**Provide `DebugInformation` (if relevant)**:
```
# Audit exception in step 1 BadResponse:
System.ArgumentException: Time expression '2.000000000e-06ms' string is invalid
Parameter name: timeUnit
   at Nest.Time.ParseExpression(String timeUnit)
   at Nest.TimeJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
```

### PR DESCRIPTION
**Pull request by Mpdreamz**
… exponent

fixes #2778

### CODE REVIEW

File: src/Nest/CommonOptions/TimeUnit/Time.cs [hunk 1]
```diff
@@ -20,7 +21,7 @@ public class Time : IComparable<Time>, IEquatable<Time>
 		private const double MicrosecondsInAMillisecond = 10;
 
 		private static readonly Regex ExpressionRegex =
-			new Regex(@"^(?<factor>[-+]?\d+(?:\.\d+)?)\s*(?<interval>(?:y|w|d|h|m|s|ms|nanos|micros))?$",
+			new Regex(@"^(?<factor>[-+]?[\d\.e\-]+?)\s*(?<interval>(?:y|w|d|h|m|s|ms|nanos|micros))?$",
```
Comment (russcam) [inline src/Nest/CommonOptions/TimeUnit/Time.cs]: How about
```
^(?<factor>[+\-]?(?:0|[1-9]\d*)(?:\.\d*)?(?:[eE][+\-]?\d+)?)\s*(?<interval>(?:y|w|d|h|m|s|ms|nanos|micros))?$
```

It's a little stricter in disallowing multiple `e`

File: src/Nest/CommonOptions/TimeUnit/Time.cs [hunk 2]
```diff
@@ -117,7 +121,7 @@ public int CompareTo(Time other)
 				// ReSharper enable PossibleInvalidOperationException
 			};
 
-			if (this.ApproximateMilliseconds == other.ApproximateMilliseconds) return 0;
+			if (Math.Abs(this.ApproximateMilliseconds - other.ApproximateMilliseconds) < FLOAT_TOLERANCE) return 0;
```
Comment (russcam) [inline src/Nest/CommonOptions/TimeUnit/Time.cs]: ++

File: src/Nest/CommonOptions/TimeUnit/Time.cs [hunk 3]
```diff
@@ -307,5 +313,16 @@ private void Reduce(double ms)
...
+
+
+		private static string ExponentFormat(double d)
+		{
+			// Translate the double into sign, exponent and mantissa.
+			var bits = BitConverter.DoubleToInt64Bits(d);
+			// Note that the shift is sign-extended, hence the test against -1 not 1
+			var exponent = (int) ((bits >> 52) & 0x7ffL);
+			return new string('#', Math.Max(2, exponent));
+		}
```
Comment (russcam) [inline src/Nest/CommonOptions/TimeUnit/Time.cs]: Is it not possible to get this from `double.ToString()` in some way?

Comment (Mpdreamz) [inline src/Nest/CommonOptions/TimeUnit/Time.cs]: I rather rely on bit shifting to get the exponent, not sure I fully understand the request here though

File: src/Nest/CommonOptions/TimeUnit/Time.cs [hunk 4]
```diff
@@ -20,7 +21,7 @@ public class Time : IComparable<Time>, IEquatable<Time>
 		private const double MicrosecondsInAMillisecond = 10;
 
 		private static readonly Regex ExpressionRegex =
-			new Regex(@"^(?<factor>[-+]?\d+(?:\.\d+)?)\s*(?<interval>(?:y|w|d|h|m|s|ms|nanos|micros))?$",
+			new Regex(@"^(?<factor>[-+]?[\d\.e\-]+?)\s*(?<interval>(?:y|w|d|h|m|s|ms|nanos|micros))?$",
 				RegexOptions.Compiled | RegexOptions.ExplicitCapture | RegexOptions.IgnoreCase);
 
 		private static double FLOAT_TOLERANCE = 0.0000001;
```
Comment (Mpdreamz) [inline src/Nest/CommonOptions/TimeUnit/Time.cs]: 👍

File: src/Nest/CommonOptions/TimeUnit/Time.cs (hunk 1 above)
Comment (Mpdreamz) [inline src/Nest/CommonOptions/TimeUnit/Time.cs]: How about `^(?<factor>[+\-]?(?:\d{1,})(?:\.(?:\d+[e][+\-]?)?\d+)?)[ ]{0,10}(?<interval>(?:y|w|d|h|m|s|ms|nanos|micros)?)$`

`(?:0|[1-9]\d*)` => `(?:\d{1,})` 
leading zeros OK i think
`(?:\.\d*)?(?:[eE][+\-]?\d+)` => `(?:\.(?:\d+[e][+\-]?)?\d+)?)`
doing insensitive matching only `e` should be fine and now with this we do not match on `123e123123` or  `123.e1231`

`\s*` => `[ ]{0,10}` 
only allow 10 spaces so we fail early on `\d<gazillion spaces>...`

Comment (russcam) [inline src/Nest/CommonOptions/TimeUnit/Time.cs]: > `(?:\d{1,})(?:\.(?:\d+[e][+\-]?)?\d+)?)` 

always requires the mantissa to include a decimal value e.g.

```
6.0e5
```
but does not match 
```
6e5
```
> doing insensitive matching only e should be fine and now with this we do not match on 123e123123 or 123.e1231

Both `123e123123` or `123.e1231` are valid notation

> `\s* => [ ]{0,10}`

Agreed, although maybe as `\s{0,10}`?

----

How about

```
^(?<factor>[+\-]?(?<mantissa>(?:\d+(\.\d*)?)|(?:\.\d+))?(?(mantissa)[e](?<exponent>[+\-]?\d+))?)\s{0,10}(?<interval>(?:y|w|d|h|m|s|ms|nanos|micros))?$
```
matches all of

```
1
+1
-1
1y
.1
1.2
1.2w
1E2
.1e2
1e-2
1.e2
1.e-2
1.2e3
1.2e-3
1.2e3d
1.2e-3h
```
and requires a number before the decimal point, after the decimal point or both. So things like

```
.e1
```
doesn't match

and also a mantissa must be present when exponential notation is used, so

```
e1
```

doesn't match

File: src/Nest/CommonOptions/TimeUnit/Time.cs (hunk 3 above)
Comment (russcam) [inline src/Nest/CommonOptions/TimeUnit/Time.cs]: I just wondered if this conversion were a public method in framework somewhere , but looks like it isn't. Ignore 😄

File: src/Nest/CommonOptions/TimeUnit/Time.cs (hunk 1 above)
Comment (Mpdreamz) [inline src/Nest/CommonOptions/TimeUnit/Time.cs]: Cool i thought those were invalid case 👍 

Only have one small addition to the regex:

`(?!^)\s{0,10}` to prevent `<leading spaces>nanos` being a match.

Comment (Mpdreamz) [inline src/Nest/CommonOptions/TimeUnit/Time.cs]: Going over it again i think your regex can be simplified like this;

`^(?<factor>[+\-]?(?<numeric>(?:\d+(?:\.\d*)?)|(?:\.\d+))(?:[e](?<exponent>[+\-]?\d+))?)\s{0,10}(?<interval>(?:y|w|d|h|m|s|ms|nanos|micros))?$`

`<numeric>` is no longer optional so the if pattern on exponent is no longer needed and the negative lookahead from my previous comment can go as well.

Comment (Mpdreamz) [inline src/Nest/CommonOptions/TimeUnit/Time.cs]: @russcam merging this in, if you have more cases for the regex to cover let me know here 👍 this was fun 😄

**Comment by Mpdreamz** [comment]
ported to `5.x` and `2.x`
