### PR TITLE
fix #3505 daterange default DateTime should not serialize

### LINKED ISSUE #3505: Incorrect query after using DateTime.MinValue in the DateRange filter
**NEST/Elasticsearch.Net version**: 6.4.0

**Elasticsearch version**: 6.5.1

**Description of the problem including expected versus actual behavior**:
I am using filter for counting documents like this

```
private static Func<QueryContainerDescriptor<ISearchableNotification>, QueryContainer> IndexedDateFromFilter(SearchQuery query)
{
    if (query.IndexedDateFrom.HasValue)
        return filter => filter.DateRange(rf => rf.Field(nm => nm.IndexedDateTime)
                                                  .GreaterThanOrEquals(query.IndexedDateFrom));
     return null;
}
```

IndexedDateFrom's type is **[DateTime?]**. When **IndexedDateFrom** equals **DateTime.MinValue** everything crashes with exception

`org.elasticsearch.ElasticsearchParseException: failed to parse date field [] with format [strict_date_optional_time||epoch_millis]`

 because NEST translates C# code into this (part of the query I got from DebugInformation)
```
{
                "range": {
                  "indexedDateTime": {
                    "gte": ""
                  }
                }
}
```

If I use **DateTime.MinValue.AddDays(1)** instead of **DateTime.MinValue** everything works fine. It looks like a bug.

### PR DESCRIPTION
**Pull request by Mpdreamz**
Pending the merge of `6.5` branch and all related PR's to that target branch.

### CODE REVIEW

**Comment by Mpdreamz** [comment]
The build is failing on travis because we need to be explicit about langversion.

Something [already fixed on `6.5`](https://github.com/elastic/elasticsearch-net/commit/c7f462c740f6a7deefffd6457b8fb7f9e679c8d6), will retarget this PR against `6.5`.

File: src/Nest/CommonOptions/DateMath/DateMath.cs [hunk 1]
```diff
@@ -79,10 +79,11 @@ public static DateMath FromString(string dateMath)
 			return math;
 		}
 
+		internal bool IsValid => Self.Anchor.Match(d => d != default, s => !s.IsNullOrEmpty());
+
 		public override string ToString()
 		{
-			var isValid = Self.Anchor.Match(d => d != default(DateTime), s => !s.IsNullOrEmpty());
-			if (!isValid) return string.Empty;
+			if (!IsValid) return string.Empty;
```
Comment (russcam) [inline src/Nest/CommonOptions/DateMath/DateMath.cs]: Should we have a separate `DateMath` test for this?

Comment (Mpdreamz) [reply src/Nest/CommonOptions/DateMath/DateMath.cs]: We should! Attached a unit test for this.
