### PR TITLE
Included the nested identity for inner hits on a nested type

### LINKED ISSUE #2323: NEST: 'Hit' type within 'InnerHits' does not include 'Nested' property with 'Offset' value
# Bug

**NEST/Elasticsearch.Net version**: 2.3.1 / 2.3.1

**Elasticsearch version**: 2.2.0

**Description of the problem including expected versus actual behavior**:
NEST: 'Hit' type within 'InnerHits' does not include 'Nested' property with 'Offset' value

**Steps to reproduce**:
- PUT /sample
- PUT /sample/_mapping/document

``` javascript
{
  "properties": {
    "sections": {
      "type": "nested",
      "properties": {
        "number": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    }
  }
}
```
- PUT /sample/document/1 

``` javascript
{
   "sections": [
      {
         "number": "one",
         "title": "Network features"
      },
      {
         "number": "two",
         "title": "Network issues"
      }
   ]
}
```
- POST /sample/document/_search

``` javascript
{
   "_source": false,
   "query": {
      "nested": {
         "query": {
            "match": {
               "sections.title": "Network"
            }
         },
         "path": "sections",
         "inner_hits": {
            "_source": false
         }
      }
   }
}
```

Expected response:

``` javascript
{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 0.625,
    "hits": [
      {
        "_index": "sample",
        "_type": "document",
        "_id": "1",
        "_score": 0.625,
        "inner_hits": {
          "sections": {
            "hits": {
              "total": 2,
              "max_score": 0.625,
              "hits": [
                {
                  "_index": "sample",
                  "_type": "document",
                  "_id": "1",
----------------  "_nested": {
|                   "field": "sections",
|                   "offset": 1
----------------  },
                  "_score": 0.625
                },
                {
                  "_index": "sample",
                  "_type": "document",
                  "_id": "1",
----------------  "_nested": {
|                   "field": "sections",
|                   "offset": 0
----------------  },
                  "_score": 0.625
                }
              ]
            }
          }
        }
      }
    ]
  }
}
```

However, neither 'Hit' nor 'InnerHitsMetaData' types does not include 'Nested' property:
https://github.com/elastic/elasticsearch-net/blob/02bdf28788e657cffc253598d7766820f9eed62e/src/Nest/Search/Search/Hits/Hit.cs
https://github.com/elastic/elasticsearch-net/blob/02bdf28788e657cffc253598d7766820f9eed62e/src/Nest/Search/Search/Hits/InnerHitsMetaData.cs

### PR DESCRIPTION
**Pull request by russcam**
See https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-aggregations-metrics-top-hits-aggregation.html#_top_hits_support_in_a_nested_or_reverse_nested_aggregator

Closes #2323

### CODE REVIEW

File: src/Tests/Reproduce/GithubIssue2323.cs [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+using FluentAssertions;
+using Nest;
+using Tests.Framework;
+using Tests.Framework.Integration;
+using Tests.Framework.MockData;
+using Xunit;
+
+namespace Tests.Reproduce
+{
+	public class GithubIssue2323 : IClusterFixture<ReadOnlyCluster>
```
Comment (Mpdreamz) [inline src/Tests/Reproduce/GithubIssue2323.cs]: Nitpick: `_nested` serialization is covered by this integration test but it'd be good to add a unit test for this too

Comment (russcam) [inline src/Tests/Reproduce/GithubIssue2323.cs]: I'll add now 👍
