### PR TITLE
Fixes integration tests against latest 7.7.0-SNAPSHOT

### LINKED ISSUE #4508: Terms lookup against 7.x-SNAPSHOT fails
https://dev.azure.com/azure3/elasticsearch-net/_build/results?buildId=3409&view=logs&j=3a52eb41-1b19-5064-cc52-fd2dc941c6b7&t=fa166c91-7209-519d-7ab9-b55c1cc5b01d&l=1283

Likely not a client bug but we should investigate before new release of Elasticsearch.

<details>
<summary>Xunit output</summary>
[xUnit.net 00:01:19.4399064]     Tests.QueryDsl.TermLevel.Terms.TermsLookupQueryUsageTests.AssertQueryResponse [FAIL]
  X Tests.QueryDsl.TermLevel.Terms.TermsLookupQueryUsageTests.AssertQueryResponse [796ms]
  Error Message:
   Expected response.IsValid to be true because Invalid NEST response built from a unsuccessful (400) low level call on POST: /project/_search?pretty=true&error_trace=true&typed_keys=true
# Audit trail of this API call:
 - [1] BadResponse: Node: http://localhost:9200/ Took: 00:00:00.0194114
# OriginalException: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: POST /project/_search?pretty=true&error_trace=true&typed_keys=true. ServerError: Type: x_content_parse_exception Reason: "[1:74] [terms_lookup] id doesn't support values of type: VALUE_NUMBER"
# Request:
{"query":{"terms":{"_name":"named_query","boost":1.1,"description":{"id":12,"index":"devs","path":"lastName","routing":"myroutingvalue"}}
# Response:
{
  "error" : {
    "root_cause" : [
      {
        "type" : "x_content_parse_exception",
        "reason" : "[1:74] [terms_lookup] id doesn't support values of type: VALUE_NUMBER",
        "stack_trace" : "[[1:74] [terms_lookup] id doesn't support values of type: VALUE_NUMBER]; nested: XContentParseException[[1:74] [terms_lookup] id doesn't support values of type: VALUE_NUMBER];\n\tat org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:644)\n\tat org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:572)\n\tat org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:138)\n\tat org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96)\n\tat org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:91)\n\tat org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:253)\n\tat org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:333)\n\tat org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:191)\n\tat org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:329)\n\tat org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:383)\n\tat org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:308)\n\tat org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:54)\n\tat org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:29)\n\tat io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n\tat org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:58)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n\tat io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat java.base/java.lang.Thread.run(Thread.java:832)\nCaused by: org.elasticsearch.common.xcontent.XContentParseException: [1:74] [terms_lookup] id doesn't support values of type: VALUE_NUMBER\n\tat org.elasticsearch.common.xcontent.ObjectParser$FieldParser.assertSupports(ObjectParser.java:580)\n\tat org.elasticsearch.common.xcontent.ObjectParser.parse(ObjectParser.java:294)\n\tat org.elasticsearch.common.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:169)\n\tat org.elasticsearch.indices.TermsLookup.parseTermsLookup(TermsLookup.java:167)\n\tat org.elasticsearch.index.query.TermsQueryBuilder.fromXContent(TermsQueryBuilder.java:377)\n\tat org.elasticsearch.search.SearchModule.lambda$registerQuery$14(SearchModule.java:871)\n\tat org.elasticsearch.common.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:140)\n\tat org.elasticsearch.common.xcontent.support.AbstractXContentParser.namedObject(AbstractXContentParser.java:385)\n\tat org.elasticsearch.index.query.AbstractQueryBuilder.parseInnerQueryBuilder(AbstractQueryBuilder.java:317)\n\tat org.elasticsearch.search.builder.SearchSourceBuilder.parseXContent(SearchSourceBuilder.java:1098)\n\tat org.elasticsearch.rest.action.search.RestSearchAction.parseSearchRequest(RestSearchAction.java:137)\n\tat org.elasticsearch.rest.action.search.RestSearchAction.lambda$prepareRequest$1(RestSearchAction.java:113)\n\tat org.elasticsearch.rest.RestRequest.withContentOrSourceParamParserOrNull(RestRequest.java:470)\n\tat org.elasticsearch.rest.action.search.RestSearchAction.prepareRequest(RestSearchAction.java:112)\n\tat org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:94)\n\tat org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:251)\n\t... 49 more\n"
      }
    ],
    "type" : "x_content_parse_exception",
    "reason" : "[1:74] [terms_lookup] id doesn't support values of type: VALUE_NUMBER",
    "stack_trace" : "org.elasticsearch.common.xcontent.XContentParseException: [1:74] [terms_lookup] id doesn't support values of type: VALUE_NUMBER\n\tat org.elasticsearch.common.xcontent.ObjectParser$FieldParser.assertSupports(ObjectParser.java:580)\n\tat org.elasticsearch.common.xcontent.ObjectParser.parse(ObjectParser.java:294)\n\tat org.elasticsearch.common.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:169)\n\tat org.elasticsearch.indices.TermsLookup.parseTermsLookup(TermsLookup.java:167)\n\tat org.elasticsearch.index.query.TermsQueryBuilder.fromXContent(TermsQueryBuilder.java:377)\n\tat org.elasticsearch.search.SearchModule.lambda$registerQuery$14(SearchModule.java:871)\n\tat org.elasticsearch.common.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:140)\n\tat org.elasticsearch.common.xcontent.support.AbstractXContentParser.namedObject(AbstractXContentParser.java:385)\n\tat org.elasticsearch.index.query.AbstractQueryBuilder.parseInnerQueryBuilder(AbstractQueryBuilder.java:317)\n\tat org.elasticsearch.search.builder.SearchSourceBuilder.parseXContent(SearchSourceBuilder.java:1098)\n\tat org.elasticsearch.rest.action.search.RestSearchAction.parseSearchRequest(RestSearchAction.java:137)\n\tat org.elasticsearch.rest.action.search.RestSearchAction.lambda$prepareRequest$1(RestSearchAction.java:113)\n\tat org.elasticsearch.rest.RestRequest.withContentOrSourceParamParserOrNull(RestRequest.java:470)\n\tat org.elasticsearch.rest.action.search.RestSearchAction.prepareRequest(RestSearchAction.java:112)\n\tat org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:94)\n\tat org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:251)\n\tat org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:333)\n\tat org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:191)\n\tat org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:329)\n\tat org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:383)\n\tat org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:308)\n\tat org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:54)\n\tat org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:29)\n\tat io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n\tat org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:58)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n\tat io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat java.base/java.lang.Thread.run(Thread.java:832)\n"
  },
  "status" : 400
}

</details>

### LINKED ISSUE #4521: Changes to Moving Average REST API
Seen: https://github.com/elastic/elasticsearch-net/pull/4503/checks?check_run_id=538335701
```

---

Tests.Aggregations.Pipeline.MovingAverage.MovingAverageHoltLinearAggregationUsageTests.ReturnsExpectedResponse
Tests.Framework.EndpointTests.ResponseAssertionException : Expected response.IsValid to be true because Invalid NEST response built from a unsuccessful (400) low level call on POST: /project/_search?pretty=true&error_trace=true&typed_keys=true
# Server indicated deprecations:
- 299 Elasticsearch-7.7.0-8fab26ad3a536257194c2b55b48064f51de55dc3 "The moving_avg aggregation has been deprecated in favor of the moving_fn aggregation."
- 299 Elasticsearch-7.7.0-8fab26ad3a536257194c2b55b48064f51de55dc3 "[interval] on [date_histogram] is deprecated, use [fixed_interval] or [calendar_interval] in the future."
# Audit trail of this API call:
 - [1] BadResponse: Node: http://localhost:9200/ Took: 00:00:00.0633842

---

Tests.Cluster.NodesInfo.NodesInfoApiTests.ReturnsExpectedStatusCode
Elasticsearch.Net.UnexpectedElasticsearchClientException : Requested value 'transform' was not found.
---- System.ArgumentException : Requested value 'transform' was not found.

---

Tests.Aggregations.Pipeline.MovingAverage.MovingAverageEwmaAggregationUsageTests.ReturnsExpectedStatusCode
Tests.Framework.EndpointTests.ResponseAssertionException : Expected response.IsValid to be true because Invalid NEST response built from a unsuccessful (400) low level call on POST: /project/_search?pretty=true&error_trace=true&typed_keys=true
# Server indicated deprecations:
- 299 Elasticsearch-7.7.0-8fab26ad3a536257194c2b55b48064f51de55dc3 "The moving_avg aggregation has been deprecated in favor of the moving_fn aggregation."
- 299 Elasticsearch-7.7.0-8fab26ad3a536257194c2b55b48064f51de55dc3 "[interval] on [date_histogram] is deprecated, use [fixed_interval] or [calendar_interval] in the future."
# Audit trail of this API call:
 - [1] BadResponse: Node: http://localhost:9200/ Took: 00:00:00.0136357
# OriginalException: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: POST /project/_search?pretty=true&error_trace=true&typed_keys=true. ServerError: Type: action_request_validation_exception Reason: "Validation Failed: 1: parent histogram of moving_avg aggregation [commits_moving_avg] must have min_doc_count of 0;"

---

Tests.Aggregations.Pipeline.MovingAverage.MovingAverageHoltWintersUsageTests.ReturnsExpectedIsValid
Tests.Framework.EndpointTests.ResponseAssertionException : Expected response.IsValid to be True because Invalid NEST response built from a unsuccessful (400) low level call on POST: /project/_search?pretty=true&error_trace=true&typed_keys=true
# Server indicated deprecations:
- 299 Elasticsearch-7.7.0-8fab26ad3a536257194c2b55b48064f51de55dc3 "The moving_avg aggregation has been deprecated in favor of the moving_fn aggregation."
- 299 Elasticsearch-7.7.0-8fab26ad3a536257194c2b55b48064f51de55dc3 "[interval] on [date_histogram] is deprecated, use [fixed_interval] or [calendar_interval] in the future."
# Audit trail of this API call:
 - [1] BadResponse: Node: http://localhost:9200/ Took: 00:00:00.1229980
# OriginalException: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: POST /project/_search?pretty=true&error_trace=true&typed_keys=true. ServerError: Type: action_request_validation_exception Reason: "Validation Failed: 1: parent histogram of moving_avg aggregation [commits_moving_avg] must have min_doc_count of 0;"


```

### PR DESCRIPTION
**Pull request by codebrain**
- Change date histogram aggregations to use minimum document = 0 in order to pass server validation.
- Changes terms query to use a string value to pass server validation
- Change search template API test to not tie to a specific server message substring

Fixes #4521 
Fixes #4508

### CODE REVIEW

File: tests/Tests/Search/SearchTemplate/SearchTemplateApiTests.cs [hunk 1]
```diff
@@ -101,13 +101,6 @@ public class SearchTemplateInvalidApiTests
...
 
-		protected override void ExpectResponse(ISearchResponse<Project> response)
-		{
-			response.ServerError.Should().NotBeNull();
-			if (TestConfiguration.Instance.ElasticsearchVersion < "7.7.0")
-				response.ServerError.Error.Reason.Should().Contain("no [query]");
-			else
-				response.ServerError.Error.Reason.Should().Contain("unknown query [atch]");
-		}
+		protected override void ExpectResponse(ISearchResponse<Project> response) => response.ServerError.Should().NotBeNull();
```
Comment (russcam) [inline tests/Tests/Search/SearchTemplate/SearchTemplateApiTests.cs:104]: maybe

```c#
response.ServerError.Error.Reason.Should().Contain("query");
```

for both? It would provide a slightly stronger assertion for why there is an error

Comment (codebrain) [reply tests/Tests/Search/SearchTemplate/SearchTemplateApiTests.cs:104]: I was just conscious that binding the test to the error message probably isn't a good idea as the error message can change.

Comment (russcam) [reply tests/Tests/Search/SearchTemplate/SearchTemplateApiTests.cs:104]: it's a fair point, historically verifiable! Is there some other way we can assert that the error is related to what we expect it to be?
