### PR TITLE
Use serializer when deserializing LazyDocument to T

### LINKED ISSUE #2788: Unable to deserialize `number` field into `TimeSpan` for inner hits
**NEST/Elasticsearch.Net version**: 5.4.0

**Elasticsearch version**: 5.4.0

**Description of the problem including expected versus actual behavior**: Unable to deserialize `number` field into `TimeSpan` for inner hits. An attempt to deserialize inner hits into object leads to an exception: `Newtonsoft.Json.JsonSerializationException: Error converting value 37230000000 to type 'System.TimeSpan'. Path 'startTime'.`

**Steps to reproduce**:
```c#
// sample mapping with nested objects with TimeSpan field
class Root
{
    [Nested]
    public Child[] Children { get; set; }
}

class Child
{
    public TimeSpan StartTime { get; set; }

    public TimeSpan EndTime { get; set; }
}

var indexName = "sample";
var client = new ElasticClient(new ConnectionSettings().DefaultIndex(indexName));

//create index with automapping
client.CreateIndex(indexName, create => create.Mappings(mappings => mappings.Map<Root>(map => map.AutoMap())));

// add sample document
client.Index(new Root
{
    Children = new[]
    {
        new Child
        {
            StartTime = new TimeSpan(1, 2, 3),
            EndTime = new TimeSpan(2, 3, 4)
        }
    }
}, index => index.Refresh(Refresh.WaitFor));

// search with inner hits
var result = client.Search<Root>(
    search => search.Query(
        query => query.Nested(
            nested => nested.Query(
                nestedQuery => nestedQuery.MatchAll()
            ).Path(i => i.Children).InnerHits()
        )
    )
);

// try to deserialize (exception)
var children = result.Hits.First().InnerHits.Single().Value.Documents<Child>();
```

### PR DESCRIPTION
**Pull request by russcam**
When converting a LazyDocument to type T, use the JsonNetSerializer configured, along with all registered contract resolvers.

Fixes #2788

### CODE REVIEW

File: src/Nest/CommonAbstractions/LazyDocument/LazyDocumentJsonConverter.cs [hunk 1]
```diff
@@ -10,19 +10,24 @@ public override void WriteJson(JsonWriter writer, object value, JsonSerializer s
 		{
 			var d = value as LazyDocument;
 			if (d?._Value == null)
+			{
+				writer.WriteNull();
```
Comment (Mpdreamz) [inline src/Nest/CommonAbstractions/LazyDocument/LazyDocumentJsonConverter.cs]: Why was this change needed?

**Comment by Mpdreamz** [comment]
Can we also add an ovlerload to fix https://github.com/elastic/elasticsearch-net/issues/2408 as part of this PR. 

Two for one :)

File: src/Nest/CommonAbstractions/LazyDocument/LazyDocumentJsonConverter.cs (hunk 1 above)
Comment (russcam) [inline src/Nest/CommonAbstractions/LazyDocument/LazyDocumentJsonConverter.cs]: I think this is an oversight in the implementation; if `d` is `null` or `d.Value` is `null` and a value is not written to the writer for it, invalid json will be emitted

**Comment by russcam** [comment]
What overload were you thinking of for #2408, @Mpdreamz?

**Comment by Mpdreamz** [comment]
https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/CommonAbstractions/LazyDocument/LazyDocument.cs#L21

Also a `As(Type T)` for dynamic invocations.

**Comment by russcam** [comment]
Gotcha

**Comment by russcam** [comment]
ported to `2.x` in c77ee31e120b49a774cf5a463c1bb0cecf2cfb58
ported to `master` in bd71ff8f27585dc1477ed9bed6f47673190b2ac5
