### PR TITLE
Low level client exception structure should match SimpleJson strategy

### LINKED ISSUE #3656: Low level client exception structure should match SimpleJson
With the move to utf8json in #3493, we should ensure that the serialized structured of an exception in the low level client matches that of SimpleJson, the preceding low level client serializer.

This may also be an opportunity to create a better exception structure, to support indexing into Elasticsearch and other logging systems.

### PR DESCRIPTION
**Pull request by russcam**
This commit introduces an ExceptionFormatters that serializes exceptions to the same structure as that used in 6.x

Fixes #3656

### CODE REVIEW

File: src/Tests/Tests/Framework/SerializationTests/ExceptionSerializationTests.cs [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+			{
+				CreateException(typeof(Exception), "outer_exception", 0),
+				CreateException(typeof(InnerException), "inner_exception", 1),
+				CreateException(typeof(InnerInnerException), "inner_inner_exception", 2),
+			};
+
+			var jArray = JArray.Parse(serialized);
+			var jArray2 = JArray.Parse(JsonConvert.SerializeObject(simpleJsonException));
+
+			JToken.DeepEquals(jArray, jArray2).Should().BeTrue();
```
Comment (Mpdreamz) [inline src/Tests/Tests/Framework/SerializationTests/ExceptionSerializationTests.cs]: Could utilize `SerializationTester.Serializes` which does the same but in case of a mismatch sorts the json and generates a nice diff exception message.

Comment (russcam) [reply src/Tests/Tests/Framework/SerializationTests/ExceptionSerializationTests.cs]: I did look at `SerializationTester`. It is heavily tied to serializing/deserializing with the client serializer, whereas this test needs to serialize with the low level client serializer
