### PR TITLE
Correctly deserialize JoinField

### LINKED ISSUE #3356: HandleNestTypesOnSourceJsonConverter does not serialize/deserialize the join field as expected
**NEST/Elasticsearch.Net version**: 6.2.0

**Elasticsearch version**: 6.x

**Description of the problem including expected versus actual behavior**:

HandleNestTypesOnSourceJsonConverter does not serialize/deserialize the join field as expected.

```
"myparent" vs "\"myparent\""
```

**Steps to reproduce**:
 1. Check attached source code
```
            var parentDocument = new MyParent
            {
                Id = 1,
                ParentProperty = "a parent prop",
                MyJoinField = "myparent"
            };

            var settings = new JsonSerializerSettings();
            settings.Converters.Add(new HandleNestTypesOnSourceJsonConverter(((IConnectionSettingsValues)connectionSettings).RequestResponseSerializer));

            var json01 = Newtonsoft.Json.JsonConvert.SerializeObject(parentDocument, Formatting.Indented, settings);
            var back01 = Newtonsoft.Json.JsonConvert.DeserializeObject<MyParent>(json01, settings);

            var json02 = Newtonsoft.Json.JsonConvert.SerializeObject(back01, Formatting.Indented, settings);

            Console.WriteLine($"JSON01: {json01}");
            Console.WriteLine($"JSON02: {json02}");
```

 2. Result

```

    JSON01: {
        "ParentProperty": "a parent prop",
        "Id": 1,
        "MyJoinField": "myparent"
    }
    JSON02: {
        "ParentProperty": "a parent prop",
        "Id": 1,
        "MyJoinField": "\"myparent\""
    }
```
 
Note: This is causing a lot of troubles for as as we use to serialize/deserialize to send documents between micro services.

### PR DESCRIPTION
**Pull request by russcam**
When the join field is a string and using JsonNetSerializer, the string
conversion should not emit the surrounding double quotes

Closes #3356

### CODE REVIEW

File: src/Tests/Tests.Reproduce/GithubIssue3356.cs [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+using Nest.JsonNetSerializer;
+
+namespace Tests.Reproduce
+{
+	public class GithubIssue3356
+	{
+		[U]
+		public void JoinFieldDeserializedCorrectly()
+		{
+			var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
```
Comment (Mpdreamz) [inline src/Tests/Tests.Reproduce/GithubIssue3356.cs]: LGTM small suggestion though is to use the recently centralized json serialization assertions.

```csharp
var tester = SerializationTester.DefaultWithSourceSerializer;
var response = tester.Client.IndexDocument(doc);
tester.AssertSerialize(response.ApiCall.RequestBodyInBytes, new { join = "parent" });
var doc = tester.AssertDeserialize<MyDocument>(response.ApiCall.RequestBodyInBytes);
```

Comment (Mpdreamz) [reply src/Tests/Tests.Reproduce/GithubIssue3356.cs]: `SerializationTester.DefaultWithSourceSerializer;` 

Would need to be added though

Comment (Mpdreamz) [reply src/Tests/Tests.Reproduce/GithubIssue3356.cs]: or even `AssertRoundTrip<MyDocument>()`
