### PR TITLE
fix #2125 bwc fix to support specifying any highlighter as string not…

### LINKED ISSUE #2125: Allow to use a custom Highlighter
In Nest 2.3.2 the `HighlightField` uses an enum `HighlighterType` as `Type`.

This prevents to use a custom highlighter instead of one of the 3 embedded within ElasticSearch.

This is a regression from Nest 1.7 where the same field was a String, therefore allowing to put the name of an highlighter provided by a plugin.

I think having a string as Type field and a few const string inside a static `HighlighterType` class would give the best of both world.

### PR DESCRIPTION
**Pull request by Mpdreamz**
… just the three buildin ones

### CODE REVIEW

File: src/Nest/Search/Search/Highlighting/HighlightField.cs [hunk 1]
```diff
@@ -47,9 +47,12 @@ public interface IHighlightField
 		[JsonProperty("boundary_chars")]
 		string BoundaryChars { get; set; }
 
-		[JsonProperty("type")]
 		HighlighterType? Type { get; set; }
 
+		[JsonProperty("type")]
+		[Obsolete("This is a temporary binary backwards compatible hack to make sure you can specify any custom highlightertype in 2.x, scheduled for removal in 5.0")]
+		string TypeHack { get; set; }
```
Comment (gmarz) [inline src/Nest/Search/Search/Highlighting/HighlightField.cs]: Again, maybe name this `CustomType`?

Comment (Mpdreamz) [inline src/Nest/Search/Search/Highlighting/HighlightField.cs]: Sounds too official in my mind, by naming it a hack explicitly we clearly signal our patch is a hack that will get removed as soon as we can.

Comment (russcam) [inline src/Nest/Search/Search/Highlighting/HighlightField.cs]: I think the application of the `Obsolete` attribute with an appropriate message identifies it as a workaround.

Comment (gmarz) [inline src/Nest/Search/Search/Highlighting/HighlightField.cs]: Agreed @russcam.  Additionally, I think `Type` and `CustomType` is a clearer distinction than `Type` and `TypeHack`, IMO.

Comment (Mpdreamz) [inline src/Nest/Search/Search/Highlighting/HighlightField.cs]: A quorem has been established :)

**Comment by Mpdreamz** [comment]
quorum*, i feel so bad right now.

File: src/Nest/Search/Search/Highlighting/HighlightField.cs (hunk 1 above)
Comment (Mpdreamz) [inline src/Nest/Search/Search/Highlighting/HighlightField.cs]: quorum*, i feel so bad right now

Comment (Mpdreamz) [inline src/Nest/Search/Search/Highlighting/HighlightField.cs]: @gmarz @forloop ready for another review

File: src/Nest/Search/Search/Highlighting/HighlightField.cs [hunk 2]
```diff
@@ -75,7 +78,12 @@ public class HighlightField : IHighlightField
 		public string TagsSchema { get; set; }
 		public bool? RequireFieldMatch { get; set; }
 		public string BoundaryChars { get; set; }
-		public HighlighterType? Type { get; set; }
+		public HighlighterType? Type
+		{
+			get { return this.CustomType.ToEnum<HighlighterType>(); }
```
Comment (gmarz) [inline src/Nest/Search/Search/Highlighting/HighlightField.cs]: Missing null check `this.CustomType?.ToEnum()`

File: src/Nest/Search/Search/Highlighting/HighlightField.cs [hunk 3]
```diff
@@ -110,7 +118,14 @@ public class HighlightFieldDescriptor<T> : DescriptorBase<HighlightFieldDescript
 
 		string IHighlightField.BoundaryChars { get; set; }
 
-		HighlighterType? IHighlightField.Type { get; set; }
+		HighlighterType? IHighlightField.Type
+		{
+#pragma warning disable CS0618 // Type or member is obsolete
+			get { return Self.CustomType.ToEnum<HighlighterType>(); }
```
Comment (gmarz) [inline src/Nest/Search/Search/Highlighting/HighlightField.cs]: missing null check here as well

File: src/Nest/Search/Search/Highlighting/HighlightField.cs (hunk 2 above)
Comment (Mpdreamz) [inline src/Nest/Search/Search/Highlighting/HighlightField.cs]: ToEnum is an extension method and is safe to call on `null`

File: src/Nest/Search/Search/Highlighting/HighlightField.cs (hunk 3 above)
Comment (Mpdreamz) [inline src/Nest/Search/Search/Highlighting/HighlightField.cs]: ToEnum is an extension method and is safe to call on `null`

Comment (gmarz) [inline src/Nest/Search/Search/Highlighting/HighlightField.cs]: ah, ok :+1: Threw me off because the previous PR had a null check, but I hadn't looked at the ToEnum() implementation, just assumed.
